//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebWCFPersonas2Cliente.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="respuesta", Namespace="http://schemas.datacontract.org/2004/07/EntityP")]
    [System.SerializableAttribute()]
    public partial class respuesta : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WebWCFPersonas2Cliente.ServiceReference1.EntPerson EntpField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ErrorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WebWCFPersonas2Cliente.ServiceReference1.EntPerson[] ListpField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MensajeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WebWCFPersonas2Cliente.ServiceReference1.EntPerson Entp {
            get {
                return this.EntpField;
            }
            set {
                if ((object.ReferenceEquals(this.EntpField, value) != true)) {
                    this.EntpField = value;
                    this.RaisePropertyChanged("Entp");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Error {
            get {
                return this.ErrorField;
            }
            set {
                if ((this.ErrorField.Equals(value) != true)) {
                    this.ErrorField = value;
                    this.RaisePropertyChanged("Error");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WebWCFPersonas2Cliente.ServiceReference1.EntPerson[] Listp {
            get {
                return this.ListpField;
            }
            set {
                if ((object.ReferenceEquals(this.ListpField, value) != true)) {
                    this.ListpField = value;
                    this.RaisePropertyChanged("Listp");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mensaje {
            get {
                return this.MensajeField;
            }
            set {
                if ((object.ReferenceEquals(this.MensajeField, value) != true)) {
                    this.MensajeField = value;
                    this.RaisePropertyChanged("Mensaje");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EntPerson", Namespace="http://schemas.datacontract.org/2004/07/EntityP")]
    [System.SerializableAttribute()]
    public partial class EntPerson : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int edadField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime fechaltaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string maternoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string palabraField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string paternoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int edad {
            get {
                return this.edadField;
            }
            set {
                if ((this.edadField.Equals(value) != true)) {
                    this.edadField = value;
                    this.RaisePropertyChanged("edad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime fechalta {
            get {
                return this.fechaltaField;
            }
            set {
                if ((this.fechaltaField.Equals(value) != true)) {
                    this.fechaltaField = value;
                    this.RaisePropertyChanged("fechalta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string materno {
            get {
                return this.maternoField;
            }
            set {
                if ((object.ReferenceEquals(this.maternoField, value) != true)) {
                    this.maternoField = value;
                    this.RaisePropertyChanged("materno");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                if ((object.ReferenceEquals(this.nombreField, value) != true)) {
                    this.nombreField = value;
                    this.RaisePropertyChanged("nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string palabra {
            get {
                return this.palabraField;
            }
            set {
                if ((object.ReferenceEquals(this.palabraField, value) != true)) {
                    this.palabraField = value;
                    this.RaisePropertyChanged("palabra");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string paterno {
            get {
                return this.paternoField;
            }
            set {
                if ((object.ReferenceEquals(this.paternoField, value) != true)) {
                    this.paternoField = value;
                    this.RaisePropertyChanged("paterno");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/obtener", ReplyAction="http://tempuri.org/IService1/obtenerResponse")]
        WebWCFPersonas2Cliente.ServiceReference1.respuesta obtener();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/obtener", ReplyAction="http://tempuri.org/IService1/obtenerResponse")]
        System.Threading.Tasks.Task<WebWCFPersonas2Cliente.ServiceReference1.respuesta> obtenerAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/obtenerid", ReplyAction="http://tempuri.org/IService1/obteneridResponse")]
        WebWCFPersonas2Cliente.ServiceReference1.respuesta obtenerid(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/obtenerid", ReplyAction="http://tempuri.org/IService1/obteneridResponse")]
        System.Threading.Tasks.Task<WebWCFPersonas2Cliente.ServiceReference1.respuesta> obteneridAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/agregar", ReplyAction="http://tempuri.org/IService1/agregarResponse")]
        WebWCFPersonas2Cliente.ServiceReference1.respuesta agregar(WebWCFPersonas2Cliente.ServiceReference1.EntPerson ep);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/agregar", ReplyAction="http://tempuri.org/IService1/agregarResponse")]
        System.Threading.Tasks.Task<WebWCFPersonas2Cliente.ServiceReference1.respuesta> agregarAsync(WebWCFPersonas2Cliente.ServiceReference1.EntPerson ep);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/editar", ReplyAction="http://tempuri.org/IService1/editarResponse")]
        WebWCFPersonas2Cliente.ServiceReference1.respuesta editar(WebWCFPersonas2Cliente.ServiceReference1.EntPerson ep);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/editar", ReplyAction="http://tempuri.org/IService1/editarResponse")]
        System.Threading.Tasks.Task<WebWCFPersonas2Cliente.ServiceReference1.respuesta> editarAsync(WebWCFPersonas2Cliente.ServiceReference1.EntPerson ep);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/eliminar", ReplyAction="http://tempuri.org/IService1/eliminarResponse")]
        WebWCFPersonas2Cliente.ServiceReference1.respuesta eliminar(WebWCFPersonas2Cliente.ServiceReference1.EntPerson ep);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/eliminar", ReplyAction="http://tempuri.org/IService1/eliminarResponse")]
        System.Threading.Tasks.Task<WebWCFPersonas2Cliente.ServiceReference1.respuesta> eliminarAsync(WebWCFPersonas2Cliente.ServiceReference1.EntPerson ep);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/buscar", ReplyAction="http://tempuri.org/IService1/buscarResponse")]
        WebWCFPersonas2Cliente.ServiceReference1.respuesta buscar(string palabra);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/buscar", ReplyAction="http://tempuri.org/IService1/buscarResponse")]
        System.Threading.Tasks.Task<WebWCFPersonas2Cliente.ServiceReference1.respuesta> buscarAsync(string palabra);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/validar", ReplyAction="http://tempuri.org/IService1/validarResponse")]
        WebWCFPersonas2Cliente.ServiceReference1.respuesta validar(WebWCFPersonas2Cliente.ServiceReference1.EntPerson ep);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/validar", ReplyAction="http://tempuri.org/IService1/validarResponse")]
        System.Threading.Tasks.Task<WebWCFPersonas2Cliente.ServiceReference1.respuesta> validarAsync(WebWCFPersonas2Cliente.ServiceReference1.EntPerson ep);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : WebWCFPersonas2Cliente.ServiceReference1.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<WebWCFPersonas2Cliente.ServiceReference1.IService1>, WebWCFPersonas2Cliente.ServiceReference1.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public WebWCFPersonas2Cliente.ServiceReference1.respuesta obtener() {
            return base.Channel.obtener();
        }
        
        public System.Threading.Tasks.Task<WebWCFPersonas2Cliente.ServiceReference1.respuesta> obtenerAsync() {
            return base.Channel.obtenerAsync();
        }
        
        public WebWCFPersonas2Cliente.ServiceReference1.respuesta obtenerid(int id) {
            return base.Channel.obtenerid(id);
        }
        
        public System.Threading.Tasks.Task<WebWCFPersonas2Cliente.ServiceReference1.respuesta> obteneridAsync(int id) {
            return base.Channel.obteneridAsync(id);
        }
        
        public WebWCFPersonas2Cliente.ServiceReference1.respuesta agregar(WebWCFPersonas2Cliente.ServiceReference1.EntPerson ep) {
            return base.Channel.agregar(ep);
        }
        
        public System.Threading.Tasks.Task<WebWCFPersonas2Cliente.ServiceReference1.respuesta> agregarAsync(WebWCFPersonas2Cliente.ServiceReference1.EntPerson ep) {
            return base.Channel.agregarAsync(ep);
        }
        
        public WebWCFPersonas2Cliente.ServiceReference1.respuesta editar(WebWCFPersonas2Cliente.ServiceReference1.EntPerson ep) {
            return base.Channel.editar(ep);
        }
        
        public System.Threading.Tasks.Task<WebWCFPersonas2Cliente.ServiceReference1.respuesta> editarAsync(WebWCFPersonas2Cliente.ServiceReference1.EntPerson ep) {
            return base.Channel.editarAsync(ep);
        }
        
        public WebWCFPersonas2Cliente.ServiceReference1.respuesta eliminar(WebWCFPersonas2Cliente.ServiceReference1.EntPerson ep) {
            return base.Channel.eliminar(ep);
        }
        
        public System.Threading.Tasks.Task<WebWCFPersonas2Cliente.ServiceReference1.respuesta> eliminarAsync(WebWCFPersonas2Cliente.ServiceReference1.EntPerson ep) {
            return base.Channel.eliminarAsync(ep);
        }
        
        public WebWCFPersonas2Cliente.ServiceReference1.respuesta buscar(string palabra) {
            return base.Channel.buscar(palabra);
        }
        
        public System.Threading.Tasks.Task<WebWCFPersonas2Cliente.ServiceReference1.respuesta> buscarAsync(string palabra) {
            return base.Channel.buscarAsync(palabra);
        }
        
        public WebWCFPersonas2Cliente.ServiceReference1.respuesta validar(WebWCFPersonas2Cliente.ServiceReference1.EntPerson ep) {
            return base.Channel.validar(ep);
        }
        
        public System.Threading.Tasks.Task<WebWCFPersonas2Cliente.ServiceReference1.respuesta> validarAsync(WebWCFPersonas2Cliente.ServiceReference1.EntPerson ep) {
            return base.Channel.validarAsync(ep);
        }
    }
}
